Repository stellar/stellar-rpc, pull requests merged in 2024-10, with the labels that each got.

#297 Remove pagingToken from getEvents
  cmd/soroban-rpc/internal/methods/get_events.go
  cmd/soroban-rpc/internal/methods/get_events_test.go
Labels: breaking-change, api-change

#264 Support two sorobans for preflight
  .github/workflows/e2e.yml
  .github/workflows/soroban-rpc.yml
  Cargo.lock
  Cargo.toml
  cmd/soroban-rpc/internal/config/main.go
  cmd/soroban-rpc/internal/config/options.go
  cmd/soroban-rpc/internal/config/toml_test.go
  cmd/soroban-rpc/internal/db/db.go
  cmd/soroban-rpc/internal/integrationtest/infrastructure/test.go
  cmd/soroban-rpc/internal/integrationtest/simulate_transaction_test.go
  cmd/soroban-rpc/internal/methods/get_transaction.go
  cmd/soroban-rpc/internal/methods/get_transaction_test.go
  cmd/soroban-rpc/internal/methods/get_transactions.go
  cmd/soroban-rpc/internal/methods/get_version_info.go
  cmd/soroban-rpc/internal/methods/simulate_transaction.go
  cmd/soroban-rpc/lib/preflight/Cargo.toml
  cmd/soroban-rpc/lib/preflight/src/lib.rs
  cmd/soroban-rpc/lib/preflight/src/shared.rs
  cmd/soroban-rpc/lib/xdr2json/Cargo.toml
  cmd/soroban-rpc/lib/xdr2json/src/lib.rs
  go.mod
  go.sum
  scripts/check-dependencies.bash
Labels: rpc-sdk-scrum, Protocol 22

#317 Add back in Protocol 22 non-breaking changes for a transition period
  cmd/soroban-rpc/internal/integrationtest/migrate_test.go
  cmd/soroban-rpc/internal/integrationtest/upgrade_test.go
  cmd/soroban-rpc/internal/methods/get_events.go
  cmd/soroban-rpc/internal/methods/get_events_test.go
  cmd/soroban-rpc/internal/methods/get_transaction.go
  cmd/soroban-rpc/internal/methods/get_transaction_test.go
  cmd/soroban-rpc/internal/methods/get_transactions.go
  cmd/soroban-rpc/internal/methods/get_transactions_test.go
  cmd/soroban-rpc/internal/methods/get_version_info.go
Labels: bug, api-change

#314 Add `txHash` field to `getTransaction` after upstream merge
  cmd/soroban-rpc/internal/methods/get_transaction.go
  cmd/soroban-rpc/internal/methods/get_transaction_test.go
Labels: bug
